export const START_GAME = 'memoryGame/START_GAME'
export const LOAD_CARDS = 'memoryGame/LOAD_CARDS'
export const SHOW_CARD = 'memoryGame/SHOW_CARD'
export const CHECK_COUPLE = 'memoryGame/CHECK_COUPLE'
export const VALID_COUPLE = 'memoryGame/VALID_COUPLE'
export const INVALID_COUPLE = 'memoryGame/HIDE_COUPLE'
export const DEFAULT_LOCALE = 'en'
